# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odev_tasarim.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 707)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1071, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btn_sec = QtWidgets.QPushButton(self.tab)
        self.btn_sec.setGeometry(QtCore.QRect(130, 470, 111, 31))
        self.btn_sec.setObjectName("btn_sec")
        self.lbl_resim_1 = QtWidgets.QLabel(self.tab)
        self.lbl_resim_1.setGeometry(QtCore.QRect(40, 150, 321, 261))
        self.lbl_resim_1.setText("")
        self.lbl_resim_1.setObjectName("lbl_resim_1")
        self.lbl_uzunluk = QtWidgets.QLabel(self.tab)
        self.lbl_uzunluk.setGeometry(QtCore.QRect(100, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lbl_uzunluk.setFont(font)
        self.lbl_uzunluk.setObjectName("lbl_uzunluk")
        self.lbl_genislik = QtWidgets.QLabel(self.tab)
        self.lbl_genislik.setGeometry(QtCore.QRect(430, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_genislik.setFont(font)
        self.lbl_genislik.setObjectName("lbl_genislik")
        self.txt_yukseklik = QtWidgets.QLineEdit(self.tab)
        self.txt_yukseklik.setGeometry(QtCore.QRect(170, 40, 131, 22))
        self.txt_yukseklik.setObjectName("txt_yukseklik")
        self.txt_genislik = QtWidgets.QLineEdit(self.tab)
        self.txt_genislik.setGeometry(QtCore.QRect(490, 40, 151, 21))
        self.txt_genislik.setObjectName("txt_genislik")
        self.lbl_resim_2 = QtWidgets.QLabel(self.tab)
        self.lbl_resim_2.setGeometry(QtCore.QRect(600, 140, 321, 261))
        self.lbl_resim_2.setText("")
        self.lbl_resim_2.setObjectName("lbl_resim_2")
        self.btn_boyutlandir = QtWidgets.QPushButton(self.tab)
        self.btn_boyutlandir.setGeometry(QtCore.QRect(710, 460, 111, 31))
        self.btn_boyutlandir.setObjectName("btn_boyutlandir")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btn_ekle = QtWidgets.QPushButton(self.tab_2)
        self.btn_ekle.setGeometry(QtCore.QRect(450, 450, 93, 28))
        self.btn_ekle.setObjectName("btn_ekle")
        self.lbl_resim_3 = QtWidgets.QLabel(self.tab_2)
        self.lbl_resim_3.setGeometry(QtCore.QRect(290, 60, 421, 351))
        self.lbl_resim_3.setText("")
        self.lbl_resim_3.setObjectName("lbl_resim_3")
        self.btn_sola_dondur = QtWidgets.QPushButton(self.tab_2)
        self.btn_sola_dondur.setGeometry(QtCore.QRect(60, 220, 93, 28))
        self.btn_sola_dondur.setObjectName("btn_sola_dondur")
        self.btn_saga_dondur = QtWidgets.QPushButton(self.tab_2)
        self.btn_saga_dondur.setGeometry(QtCore.QRect(820, 220, 93, 28))
        self.btn_saga_dondur.setObjectName("btn_saga_dondur")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lbl_resim_4 = QtWidgets.QLabel(self.tab_3)
        self.lbl_resim_4.setGeometry(QtCore.QRect(30, 20, 281, 221))
        self.lbl_resim_4.setText("")
        self.lbl_resim_4.setObjectName("lbl_resim_4")
        self.lbl_resim_5 = QtWidgets.QLabel(self.tab_3)
        self.lbl_resim_5.setGeometry(QtCore.QRect(30, 330, 281, 221))
        self.lbl_resim_5.setText("")
        self.lbl_resim_5.setObjectName("lbl_resim_5")
        self.btn_ekle_resim = QtWidgets.QPushButton(self.tab_3)
        self.btn_ekle_resim.setGeometry(QtCore.QRect(120, 260, 93, 28))
        self.btn_ekle_resim.setObjectName("btn_ekle_resim")
        self.btn_ekle_resim_2 = QtWidgets.QPushButton(self.tab_3)
        self.btn_ekle_resim_2.setGeometry(QtCore.QRect(110, 580, 93, 28))
        self.btn_ekle_resim_2.setObjectName("btn_ekle_resim_2")
        self.lbl_resim_6 = QtWidgets.QLabel(self.tab_3)
        self.lbl_resim_6.setGeometry(QtCore.QRect(700, 50, 281, 221))
        self.lbl_resim_6.setText("")
        self.lbl_resim_6.setObjectName("lbl_resim_6")
        self.cm_box = QtWidgets.QComboBox(self.tab_3)
        self.cm_box.setGeometry(QtCore.QRect(460, 120, 141, 22))
        self.cm_box.setCurrentText("")
        self.cm_box.setObjectName("cm_box")
        self.btn_uygula = QtWidgets.QPushButton(self.tab_3)
        self.btn_uygula.setGeometry(QtCore.QRect(460, 170, 141, 28))
        self.btn_uygula.setObjectName("btn_uygula")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.btn_gozat = QtWidgets.QPushButton(self.tab_4)
        self.btn_gozat.setGeometry(QtCore.QRect(70, 460, 93, 28))
        self.btn_gozat.setObjectName("btn_gozat")
        self.lbl_resim_7 = QtWidgets.QLabel(self.tab_4)
        self.lbl_resim_7.setGeometry(QtCore.QRect(30, 80, 381, 331))
        self.lbl_resim_7.setText("")
        self.lbl_resim_7.setObjectName("lbl_resim_7")
        self.lbl_resim_8 = QtWidgets.QLabel(self.tab_4)
        self.lbl_resim_8.setGeometry(QtCore.QRect(650, 80, 381, 331))
        self.lbl_resim_8.setText("")
        self.lbl_resim_8.setObjectName("lbl_resim_8")
        self.cm_box_2 = QtWidgets.QComboBox(self.tab_4)
        self.cm_box_2.setGeometry(QtCore.QRect(440, 140, 171, 22))
        self.cm_box_2.setObjectName("cm_box_2")
        self.btn_filtre_uygula = QtWidgets.QPushButton(self.tab_4)
        self.btn_filtre_uygula.setGeometry(QtCore.QRect(440, 170, 171, 28))
        self.btn_filtre_uygula.setObjectName("btn_filtre_uygula")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.btn_resim_sec = QtWidgets.QPushButton(self.tab_5)
        self.btn_resim_sec.setGeometry(QtCore.QRect(160, 310, 93, 28))
        self.btn_resim_sec.setObjectName("btn_resim_sec")
        self.lbl_resim_9 = QtWidgets.QLabel(self.tab_5)
        self.lbl_resim_9.setGeometry(QtCore.QRect(40, 50, 351, 231))
        self.lbl_resim_9.setText("")
        self.lbl_resim_9.setObjectName("lbl_resim_9")
        self.lbl_resim_10 = QtWidgets.QLabel(self.tab_5)
        self.lbl_resim_10.setGeometry(QtCore.QRect(670, 40, 341, 321))
        self.lbl_resim_10.setText("")
        self.lbl_resim_10.setObjectName("lbl_resim_10")
        self.btn_lableling = QtWidgets.QPushButton(self.tab_5)
        self.btn_lableling.setGeometry(QtCore.QRect(450, 190, 161, 28))
        self.btn_lableling.setObjectName("btn_lableling")
        self.lbl_resim_13 = QtWidgets.QLabel(self.tab_5)
        self.lbl_resim_13.setGeometry(QtCore.QRect(380, 530, 341, 321))
        self.lbl_resim_13.setText("")
        self.lbl_resim_13.setObjectName("lbl_resim_13")
        self.lbl_detected = QtWidgets.QLabel(self.tab_5)
        self.lbl_detected.setGeometry(QtCore.QRect(40, 360, 361, 201))
        self.lbl_detected.setText("")
        self.lbl_detected.setObjectName("lbl_detected")
        self.btn_gozat_resim = QtWidgets.QPushButton(self.tab_5)
        self.btn_gozat_resim.setGeometry(QtCore.QRect(160, 590, 93, 28))
        self.btn_gozat_resim.setObjectName("btn_gozat_resim")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.btn_labelling_sec = QtWidgets.QPushButton(self.tab_8)
        self.btn_labelling_sec.setGeometry(QtCore.QRect(140, 360, 101, 28))
        self.btn_labelling_sec.setObjectName("btn_labelling_sec")
        self.label_resim_sec = QtWidgets.QLabel(self.tab_8)
        self.label_resim_sec.setGeometry(QtCore.QRect(20, 40, 351, 291))
        self.label_resim_sec.setText("")
        self.label_resim_sec.setObjectName("label_resim_sec")
        self.btn_labelling_uygula = QtWidgets.QPushButton(self.tab_8)
        self.btn_labelling_uygula.setGeometry(QtCore.QRect(640, 350, 121, 28))
        self.btn_labelling_uygula.setObjectName("btn_labelling_uygula")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.btn_resim_ekle = QtWidgets.QPushButton(self.tab_6)
        self.btn_resim_ekle.setGeometry(QtCore.QRect(70, 470, 93, 28))
        self.btn_resim_ekle.setObjectName("btn_resim_ekle")
        self.lbl_resim_11 = QtWidgets.QLabel(self.tab_6)
        self.lbl_resim_11.setGeometry(QtCore.QRect(40, 50, 361, 351))
        self.lbl_resim_11.setText("")
        self.lbl_resim_11.setObjectName("lbl_resim_11")
        self.lbl_resim_12 = QtWidgets.QLabel(self.tab_6)
        self.lbl_resim_12.setGeometry(QtCore.QRect(620, 40, 361, 351))
        self.lbl_resim_12.setText("")
        self.lbl_resim_12.setObjectName("lbl_resim_12")
        self.btn_gurultu = QtWidgets.QPushButton(self.tab_6)
        self.btn_gurultu.setGeometry(QtCore.QRect(760, 460, 101, 28))
        self.btn_gurultu.setObjectName("btn_gurultu")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.btn_daire_ciz = QtWidgets.QPushButton(self.tab_7)
        self.btn_daire_ciz.setGeometry(QtCore.QRect(490, 70, 93, 28))
        self.btn_daire_ciz.setObjectName("btn_daire_ciz")
        self.lbl_cember = QtWidgets.QLabel(self.tab_7)
        self.lbl_cember.setGeometry(QtCore.QRect(140, 150, 791, 431))
        self.lbl_cember.setText("")
        self.lbl_cember.setObjectName("lbl_cember")
        self.lbl_merkez_koordinat = QtWidgets.QLabel(self.tab_7)
        self.lbl_merkez_koordinat.setGeometry(QtCore.QRect(20, 70, 131, 16))
        self.lbl_merkez_koordinat.setObjectName("lbl_merkez_koordinat")
        self.txt_koordinat = QtWidgets.QLineEdit(self.tab_7)
        self.txt_koordinat.setGeometry(QtCore.QRect(170, 70, 241, 22))
        self.txt_koordinat.setObjectName("txt_koordinat")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.buton_resim_sec = QtWidgets.QPushButton(self.tab_9)
        self.buton_resim_sec.setGeometry(QtCore.QRect(130, 390, 93, 28))
        self.buton_resim_sec.setObjectName("buton_resim_sec")
        self.label_resim_goster = QtWidgets.QLabel(self.tab_9)
        self.label_resim_goster.setGeometry(QtCore.QRect(20, 40, 321, 321))
        self.label_resim_goster.setText("")
        self.label_resim_goster.setObjectName("label_resim_goster")
        self.label_piksel = QtWidgets.QLabel(self.tab_9)
        self.label_piksel.setGeometry(QtCore.QRect(390, 80, 671, 20))
        self.label_piksel.setObjectName("label_piksel")
        self.btn_piksel_bul = QtWidgets.QPushButton(self.tab_9)
        self.btn_piksel_bul.setGeometry(QtCore.QRect(452, 210, 111, 28))
        self.btn_piksel_bul.setObjectName("btn_piksel_bul")
        self.tabWidget.addTab(self.tab_9, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_sec.setText(_translate("Dialog", "Resim Seç"))
        self.lbl_uzunluk.setText(_translate("Dialog", "Height"))
        self.lbl_genislik.setText(_translate("Dialog", "Width"))
        self.btn_boyutlandir.setText(_translate("Dialog", "Boyutlandır"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Boyutlandırma"))
        self.btn_ekle.setText(_translate("Dialog", "Resim Ekle"))
        self.btn_sola_dondur.setText(_translate("Dialog", "Sola Döndür"))
        self.btn_saga_dondur.setText(_translate("Dialog", "Sağa Döndür"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Resim Döndürme"))
        self.btn_ekle_resim.setText(_translate("Dialog", "Resim Seç"))
        self.btn_ekle_resim_2.setText(_translate("Dialog", "Resim Seç"))
        self.btn_uygula.setText(_translate("Dialog", "Gerçekleştir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Mantıksal İşlemler"))
        self.btn_gozat.setText(_translate("Dialog", "Resim Seç"))
        self.btn_filtre_uygula.setText(_translate("Dialog", "Filtre Uygula"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Filtreleme"))
        self.btn_resim_sec.setText(_translate("Dialog", "Resim Seç"))
        self.btn_lableling.setText(_translate("Dialog", "Template Matching Uygula"))
        self.btn_gozat_resim.setText(_translate("Dialog", "Resim Seç"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Template Matching"))
        self.btn_labelling_sec.setText(_translate("Dialog", "Resim Seç"))
        self.btn_labelling_uygula.setText(_translate("Dialog", "Labelling Uygula"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Dialog", "Labelling"))
        self.btn_resim_ekle.setText(_translate("Dialog", "Resim Seç"))
        self.btn_gurultu.setText(_translate("Dialog", "Gürültü Oluştur"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Gürültü Ekleme"))
        self.btn_daire_ciz.setText(_translate("Dialog", "Daire Çiz"))
        self.lbl_merkez_koordinat.setText(_translate("Dialog", "Merkez Koordinatları:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Daire Çizme"))
        self.buton_resim_sec.setText(_translate("Dialog", "Resim Seç"))
        self.label_piksel.setText(_translate("Dialog", "TextLabel"))
        self.btn_piksel_bul.setText(_translate("Dialog", "Pikselleri Yazdır"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("Dialog", "Piksel Elde Etme"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

